### ISSUE TITLE
Text off center for certain initials

### ISSUE THREAD

**Issue by tenfef** [a6digital/laravel-default-profile-image#2]
Hi mate,

Love the library. A few of the initials are being generated slightly off center and it is killing me haha.
You can see it with PB and a few others more obviously, but I think they are all off center slightly.

![pbde8cc3_60](https://cloud.githubusercontent.com/assets/1075450/8898409/00f8a76c-3478-11e5-8ef5-3416c998c1da.png)

Any ideas what would be causing this?

Cheers

**Comment by toprakkaya** [comment]
Hi mate,
You are right :)
If you look up the source code of the main class ( src/A6digital/Image/DefaultProfileImage.php ), you see that image creation class uses just Intervention Image Library. No more no less. I think there is a centring font problem in Intervention Image Library.
